name: flutter_demo
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # https://fijkplayer.befovy.com/docs/zh/install.html#gsc.tab=0
  fijkplayer: ^0.11.0
  carousel_slider: ^4.2.1
  marquee: ^2.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  dio: ^5.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # https://github.com/letsar/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.7.0
  # https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.4
  # http://tool.chacuo.net/cryptaes/
  encrypt: ^5.0.1
  flutter_markdown: ^0.6.17+1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - resources/
  fonts:
    - family: HarmonyOS-Sans
      fonts:
        - asset: fonts/HarmonyOS-Sans-Regular.ttf
        - asset: fonts/HarmonyOS-Sans-Medium.ttf
          weight: 500
